# Generated by Django 3.0.7 on 2020-10-14 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_auto_20201014_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
